/**
 * Error IDs for Sentry tracking and debugging
 *
 * Grouped by feature/module for easy tracking.
 * Format: <MODULE>_<ERROR_TYPE>_<SPECIFIC_CASE>
 *
 * Usage:
 * ```typescript
 * import { ANIM_NOT_INIT } from '@/constants/errorIds';
 *
 * console.error('[AnimationManager] Not initialized', {
 *   errorId: ANIM_NOT_INIT,
 *   visualId,
 * });
 * ```
 */

// Animation errors
export const ANIM_NOT_INIT = 'ANIM_NOT_INIT';
export const ANIM_VISUAL_NOT_FOUND = 'ANIM_VISUAL_NOT_FOUND';
export const ANIM_TICKER_CRITICAL = 'ANIM_TICKER_CRITICAL';
export const ANIM_UPDATE_FAILED = 'ANIM_UPDATE_FAILED';
export const ANIM_CHILD_NOT_FOUND = 'ANIM_CHILD_NOT_FOUND';
export const ANIM_CHILD_WRONG_TYPE = 'ANIM_CHILD_WRONG_TYPE';
export const ANIM_NO_UPDATER = 'ANIM_NO_UPDATER';
export const ANIM_TIMEOUT = 'ANIM_TIMEOUT';

// Shuffle errors
export const SHUFFLE_STACK_NOT_FOUND = 'SHUFFLE_STACK_NOT_FOUND';
export const SHUFFLE_INVALID_TYPE = 'SHUFFLE_INVALID_TYPE';
export const SHUFFLE_INSUFFICIENT_CARDS = 'SHUFFLE_INSUFFICIENT_CARDS';
export const SHUFFLE_GHOST_CREATE_FAILED = 'SHUFFLE_GHOST_CREATE_FAILED';
export const SHUFFLE_ANIM_NOT_FOUND = 'SHUFFLE_ANIM_NOT_FOUND';
export const SHUFFLE_DETECT_INVALID_ARRAY = 'SHUFFLE_DETECT_INVALID_ARRAY';
export const SHUFFLE_DETECT_FAILED = 'SHUFFLE_DETECT_FAILED';

// Object update errors
export const FLIP_MIDPOINT_FAILED = 'FLIP_MIDPOINT_FAILED';
export const FLIP_COMPLETE_FAILED = 'FLIP_COMPLETE_FAILED';
export const SHUFFLE_COMPLETE_FAILED = 'SHUFFLE_COMPLETE_FAILED';

// Texture loading errors
export const TEXTURE_FETCH_FAILED = 'TEXTURE_FETCH_FAILED';
export const TEXTURE_DECODE_FAILED = 'TEXTURE_DECODE_FAILED';
export const TEXTURE_CREATE_FAILED = 'TEXTURE_CREATE_FAILED';
export const TEXTURE_LOAD_FAILED = 'TEXTURE_LOAD_FAILED';

// Card image errors
export const CARD_IMAGE_NOT_FOUND = 'CARD_IMAGE_NOT_FOUND';
export const CARD_IMAGE_NO_FACE = 'CARD_IMAGE_NO_FACE';
export const CARD_IMAGE_NO_BACK = 'CARD_IMAGE_NO_BACK';

// Awareness errors
export const AWARENESS_UPDATE_FAILED = 'AWARENESS_UPDATE_FAILED';
export const AWARENESS_RENDER_FAILED = 'AWARENESS_RENDER_FAILED';
export const AWARENESS_CLEAR_FAILED = 'AWARENESS_CLEAR_FAILED';
export const AWARENESS_GHOST_RENDER_FAILED = 'AWARENESS_GHOST_RENDER_FAILED';
export const AWARENESS_GHOST_OBJECT_MISSING = 'AWARENESS_GHOST_OBJECT_MISSING';

// Plugin loading errors
export const PLUGIN_REGISTRY_FETCH_FAILED = 'PLUGIN_REGISTRY_FETCH_FAILED';
export const PLUGIN_REGISTRY_PARSE_FAILED = 'PLUGIN_REGISTRY_PARSE_FAILED';
export const PLUGIN_REGISTRY_INVALID = 'PLUGIN_REGISTRY_INVALID';
export const PLUGIN_MANIFEST_FETCH_FAILED = 'PLUGIN_MANIFEST_FETCH_FAILED';
export const PLUGIN_MANIFEST_PARSE_FAILED = 'PLUGIN_MANIFEST_PARSE_FAILED';
export const PLUGIN_MANIFEST_INVALID = 'PLUGIN_MANIFEST_INVALID';
export const PLUGIN_NOT_FOUND = 'PLUGIN_NOT_FOUND';
export const PLUGIN_LOCAL_DIRECTORY_CANCELLED =
  'PLUGIN_LOCAL_DIRECTORY_CANCELLED';
export const PLUGIN_LOCAL_NO_INDEX = 'PLUGIN_LOCAL_NO_INDEX';
export const PLUGIN_LOCAL_INDEX_PARSE_FAILED =
  'PLUGIN_LOCAL_INDEX_PARSE_FAILED';
export const PLUGIN_LOCAL_FILE_NOT_FOUND = 'PLUGIN_LOCAL_FILE_NOT_FOUND';
export const PLUGIN_LOCAL_FILE_READ_FAILED = 'PLUGIN_LOCAL_FILE_READ_FAILED';
export const PLUGIN_LOCAL_INCOMPLETE = 'PLUGIN_LOCAL_INCOMPLETE';

// Asset pack errors
export const ASSETPACK_FETCH_FAILED = 'ASSETPACK_FETCH_FAILED';
export const ASSETPACK_PARSE_FAILED = 'ASSETPACK_PARSE_FAILED';
export const ASSETPACK_INVALID_SCHEMA = 'ASSETPACK_INVALID_SCHEMA';

// Scenario errors
export const SCENARIO_FETCH_FAILED = 'SCENARIO_FETCH_FAILED';
export const SCENARIO_PARSE_FAILED = 'SCENARIO_PARSE_FAILED';
export const SCENARIO_INVALID_SCHEMA = 'SCENARIO_INVALID_SCHEMA';
export const SCENARIO_INSTANTIATE_FAILED = 'SCENARIO_INSTANTIATE_FAILED';
export const SCENARIO_OBJECT_ADD_FAILED = 'SCENARIO_OBJECT_ADD_FAILED';

// Content system errors
export const CONTENT_GAME_NOT_FOUND = 'CONTENT_GAME_NOT_FOUND';
export const CONTENT_GAMES_INDEX_FETCH_FAILED =
  'CONTENT_GAMES_INDEX_FETCH_FAILED';
export const CONTENT_GAMES_INDEX_PARSE_FAILED =
  'CONTENT_GAMES_INDEX_PARSE_FAILED';
export const CONTENT_RELOAD_INVALID_METADATA =
  'CONTENT_RELOAD_INVALID_METADATA';
export const CONTENT_RELOAD_LOCAL_DEV_UNSUPPORTED =
  'CONTENT_RELOAD_LOCAL_DEV_UNSUPPORTED';
export const CONTENT_RELOAD_UNKNOWN_TYPE = 'CONTENT_RELOAD_UNKNOWN_TYPE';
export const CONTENT_TABLE_MOUNT_LOAD_FAILED =
  'CONTENT_TABLE_MOUNT_LOAD_FAILED';
export const CONTENT_REMOTE_SCENARIO_LOAD_FAILED =
  'CONTENT_REMOTE_SCENARIO_LOAD_FAILED';

// Action errors
export const ACTION_LOAD_SCENARIO_FAILED = 'ACTION_LOAD_SCENARIO_FAILED';
export const ACTION_LOAD_PLUGIN_DIRECTORY_FAILED =
  'ACTION_LOAD_PLUGIN_DIRECTORY_FAILED';
export const ACTION_LOAD_MARVELCHAMPIONS_FAILED =
  'ACTION_LOAD_MARVELCHAMPIONS_FAILED';

// Store errors
export const STORE_GAMEASSETS_LISTENER_FAILED =
  'STORE_GAMEASSETS_LISTENER_FAILED';
