/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as PixitestRouteImport } from './routes/pixitest'
import { Route as TableIdRouteImport } from './routes/table.$id'
import { Route as DevTableIdRouteImport } from './routes/dev.table.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const PixitestRoute = PixitestRouteImport.update({
  id: '/pixitest',
  path: '/pixitest',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIdRoute = TableIdRouteImport.update({
  id: '/table/$id',
  path: '/table/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTableIdRoute = DevTableIdRouteImport.update({
  id: '/dev/table/$id',
  path: '/dev/table/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/pixitest': typeof PixitestRoute
  '/table/$id': typeof TableIdRoute
  '/dev/table/$id': typeof DevTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/pixitest': typeof PixitestRoute
  '/table/$id': typeof TableIdRoute
  '/dev/table/$id': typeof DevTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/pixitest': typeof PixitestRoute
  '/table/$id': typeof TableIdRoute
  '/dev/table/$id': typeof DevTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnostic' | '/pixitest' | '/table/$id' | '/dev/table/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnostic' | '/pixitest' | '/table/$id' | '/dev/table/$id'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/pixitest'
    | '/table/$id'
    | '/dev/table/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  PixitestRoute: typeof PixitestRoute
  TableIdRoute: typeof TableIdRoute
  DevTableIdRoute: typeof DevTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixitest': {
      id: '/pixitest'
      path: '/pixitest'
      fullPath: '/pixitest'
      preLoaderRoute: typeof PixitestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$id': {
      id: '/table/$id'
      path: '/table/$id'
      fullPath: '/table/$id'
      preLoaderRoute: typeof TableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/table/$id': {
      id: '/dev/table/$id'
      path: '/dev/table/$id'
      fullPath: '/dev/table/$id'
      preLoaderRoute: typeof DevTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  PixitestRoute: PixitestRoute,
  TableIdRoute: TableIdRoute,
  DevTableIdRoute: DevTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
